<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit|ie-comp|ie-stand">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width">
</head>
<style>
    html{height: 100%;}
    body{margin: 0;padding: 0;height: 100%;font-family: }
    .audio-content{height: 100%;text-align: center;}
    p{margin: 0;padding: 0;}
    .header{height: 80%;}
    .footer{height: 20%;}
    .time{color: #54b73a;font-size: 36px;}
    .time-content{padding-top: 50%;}
    .audio-btn{outline: none;cursor: pointer; width: 80%;height: 50px;background: #bababa;color: white;font-size: 18px;border-radius: 6px;margin-bottom: 8px;}
    .start-btn{background: #54b73a;}

</style>
<body>
<div class="audio-content">
    <div class="header">
        <div class="time-content">
            <p class="shibie"></p>
            <p class="time">
                00:00:00
            </p>
            <p class="text">请点击开始录音按钮录音~</p>
        </div>
    </div>
    <div class="footer">
        <button type="button" class="audio-btn start-btn">开始录音</button>
        <button type="button" class="audio-btn cancel">取消</button>
    </div>
</div>
</body>
<script src="https://cdn.bootcss.com/jquery/1.9.1/jquery.min.js"></script>
<script src="/js/index/ios-weixin-config.js"></script>
<script src="/js/index/app.js"></script>
<script>
    RecordApp.RequestPermission(function(){
        RecordApp.Start({},function(){//使用默认配置开始录音，mp3格式
            setTimeout(function(){
                RecordApp.Stop(function(blob,duration){//到达指定条件停止录音
                    console.log(URL.createObjectURL(blob),"时长:"+duration+"ms");

                    //已经拿到blob文件对象想干嘛就干嘛：立即播放、上传
                },function(msg){
                    console.log("录音失败:"+msg);
                });
            },3000);
        },function(msg){
            console.log("开始录音失败："+msg);
        });
    },function(msg,isUserNotAllow){//用户拒绝未授权或不支持
        console.log((isUserNotAllow?"UserNotAllow，":"")+"无法录音:"+msg);
    });
</script>
</html>