
<!doctype html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Storage 上传 Demo</title>
    <link rel="stylesheet" href="//cdn.bootcss.com/bootstrap/3.3.6/css/bootstrap.min.css">
</head>
<body>

<div class="container">
    <div class="row">

        <div class="col-md-6 col-md-offset-3">
            <div class="jumbotron">
                <h1>上传Demo</h1>
            </div>
        </div>

        <div class="col-md-4 col-md-offset-4">

            <div class="progress">
                <div class="progress-bar progress-bar-success progress-bar-striped  active"  id='progress' role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%">
                </div>
            </div>

            <div class="text-center" id="upload-percent-text"></div>

            <div class="form-group">
                <input type="file" class='form-control' id='file' multiple="multiple">
            </div>
            <div class="form-group">
                <button id='submit' class='btn btn-success' onclick="UpladFile()">上传</button>
            </div>
        </div>
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-success">
                <div class="panel-body" id="upload-complete-text"></div>
            </div>
        </div>
    </div>
</div>

<script src="//cdn.bootcss.com/jquery/2.2.4/jquery.min.js"></script>
<script>
    function UpladFile() {
        var fileObj = document.getElementById("file").files[0]; // js 获取文件对象
        var url =  "/oss/index/upload"; // 接收上传文件的后台地址

        var form = new FormData(); // FormData 对象
        form.append("file", fileObj); // 文件对象

        xhr = new XMLHttpRequest();  // XMLHttpRequest 对象
        xhr.open("post", url, true); //post方式，url为服务器请求地址，true 该参数规定请求是否异步处理。

        xhr.send(form); //开始上传，发送form数据
    }
</script>
</body>
</html>

