<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit|ie-comp|ie-stand">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width">
    <title><?php echo isset($data['title']) ? $data['title'] : "激励系统";?></title>
    <link rel="stylesheet" href="//at.alicdn.com/t/font_704254_gceav6z3nfi.css" type="text/css">
    <link rel="stylesheet" href="/css/layout/layout.css" type="text/css" />
    <link rel="stylesheet" href="/css/common/Myalert.css" type="text/css" />
    <script type="text/javascript" src="/js/common/jquery.min.js"></script>
    <script src="/js/common/Myalert.js"></script>
</head>
<body>
<div id="hr_top">
    <!--    <span>--><?php //if($plume['after']['user']){echo $plume['after']['user']['comp_name'];}?><!--</span>-->
    <span>激励系统</span>
</div>
<div class="hr-sidebar">
    <div class="hr-sidebar-menu">
        <div class="hr-item">
            <!--<a class="hr-item-a" href="JavaScript:;">
                <span>员工管理</span>
                <span class="arrow"></span>
            </a>-->
            <div class="hr-vertical-menu">
                <a href="/ugs/index/index">
                    <span>积分管理</span>
                </a>
            </div>
            <!--<div class="hr-vertical-menu">
                <a href="javascript:;">
                    <span>成就管理</span>
                </a>
            </div>
            <div class="hr-vertical-menu">
                <a href="javascript:;">
                    <span>等级管理</span>
                </a>
            </div>-->
        </div>
      <!--  <div class="hr-item">
            <a class="hr-item-a" href="JavaScript:;">
                <span>招聘管理</span>
                <span class="arrow"></span>
            </a>
            <div class="hr-vertical-menu">
                <a href="/arkhr/recruitment/index">
                    <span>招聘管理</span>
                </a>
            </div>
        </div>-->
    </div>
</div>
<script src="/js/layout/layout.js"></script>

